### ISSUE TITLE
Lecture 4 setup code

### ISSUE THREAD

**Issue by kamiradi** [learningadaptivereactiverobotcontrol/book-code#2]
Hi,

I am having trouble running your setup code for the exercises on lecture 4 (learning control laws). I believe the `lightspeed` tests have a hard-coded path somewhere, because of which running the `setup_chp3(1).m` command runs into the following error:

```
Invalid MEX-file '/MATLAB Drive/LARRC/libraries/book-thirdparty/lightspeed/randgamma.mexa64':
/home/maxime/Workspace/larrc-course-code/matlab_exercises/libraries/book-thirdparty/lightspeed/librandom.so: cannot open shared object file: No such file or directory

Error in [test_randgamma](matlab:matlab.internal.language.introspective.errorDocCallback('test_randgamma', '/MATLAB Drive/LARRC/libraries/book-thirdparty/lightspeed/tests/test_randgamma.m', 2)) ([line 2](matlab: opentoline('/MATLAB Drive/LARRC/libraries/book-thirdparty/lightspeed/tests/test_randgamma.m',2,0)))
x = randgamma(repmat(a,1,10000));

Error in [test_lightspeed](matlab:matlab.internal.language.introspective.errorDocCallback('test_lightspeed', '/MATLAB Drive/LARRC/libraries/book-thirdparty/lightspeed/tests/test_lightspeed.m', 14)) ([line 14](matlab: opentoline('/MATLAB Drive/LARRC/libraries/book-thirdparty/lightspeed/tests/test_lightspeed.m',14,0)))
test_randgamma

Error in [setup_code_ch3](matlab:matlab.internal.language.introspective.errorDocCallback('setup_code_ch3', '/MATLAB Drive/LARRC/lecture4-learning-control-laws/setup_code_ch3.m', 90)) ([line 90](matlab: opentoline('/MATLAB Drive/LARRC/lecture4-learning-control-laws/setup_code_ch3.m',90,0)))
test_lightspeed
```

I am running your code on the MATLAB online portal. How can I get rid of this error?

Thank you for your work and instruction.

**Comment by Maxime00** [comment]
Hi,

Indeed the compiled mex file has a hard-coded path from the computer where it was compiled. 
Did you check you have an installed mex compiler by typing 'mex -setup' in the MATLAB command window?

This is usually not an issue with Windows OS but can be with Unix or Mac. Which OS are you using?
If you are on Mac, make sure you follow the additional instructions.

The straightforward solution is to remove the randgamma.mexa64 file given in the first line of your error so you can recompile it on your own computer, using setup_code_ch3(1).

In any case, the lightspeed library is only necessary to speed up calculations, so you should be able to run the rest of the code regardless, albeit more slowly. 

Please let me know if this worked, or if I can help any other way!

**Comment by Maxime00** [comment]
Hi,

Please disregard my previous comment!

After testing on MATLAB Online, it seems the issue actually stemmed from the space in the 'MATLAB Drive/' path. 
I've fixed the installation code in the latest commit, so please git pull the changes and try again.

Let me know how it goes :)

**Comment by kamiradi** [comment]
Hi @Maxime00, apologies for the delayed response. I tried the new commit today, it seems to be running into the same issue. The error of the space in the 'MATLAB Drive/' path persists.

My workflow is that I have a local copy of the repository that I have synced with MATLAB Drive using the Matlab connector application. I can change the workflow to try it out locally, however I have a feeling many students and researchers trying out the book code may have a similar online workflow. 

Let me know if there is anything I can do to help. :)

**Comment by Maxime00** [comment]
Hi @kamiradi,

Indeed, I would like to resolve this issue properly. 

What OS are you using?
Are you sure you are recompiling your mex files when running setup_code_ch3(1)?
Could you please provide the exact error you are getting?
Could you also provide the output from typing 'mex -setup' in the MATLAB command window?

Thank you!

**Comment by kamiradi** [comment]
Hi @Maxime00,

Apologies, I did not recompile the mex files with running `setup_code_ch3(1)`. It is now recompiling and everything seems to be in order.

Maybe adding this additional instruction for Matlab online users in the `instructions.pdf` may point users to running this additional step.

The following is the complete specification of my usage:
OS: Ubuntu 20.04
Matlab version: Current version of Matlab Online
Workflow: Forked and cloned copy of the repository on the local machine that is synced using Matlab connector with Matlab Drive.

Thank you for your help and instruction
