### ISSUE TITLE
Can we find the solution somewhere?

### ISSUE THREAD

**Issue by edward9503** [learningadaptivereactiverobotcontrol/book-code#3]
Hi, 

Thanks for sharing all the materials of this excellent course. I was wondering if we can find the solution of the matlab code somewhere, like from the book? Many thanks in advance.

**Comment by Maxime00** [comment]
Hi,

Only the solutions to Practicals I and II are publicly available on a separate branch. You can find complete code to better understand lectures 4, 6 and 7 there.

All others solutions must be requested through the MIT Press portal, for lecturers having purchased the book. You can request the solutions [here](https://mitpress.mit.edu/books/learning-adaptive-and-reactive-robot-control) by clicking on ‘Digital Exam/Desk Copy’ and choosing supplemental materials afterwards.
